### PR TITLE
Update database

### LINKED ISSUE #15: Update database
# REQUIREMENTS
- Create admin model
- Create reports model
- Update employee model
- Update branch model

# DESIGN
image

### PR DESCRIPTION
**Pull request by Javi1499**
# Description
What did you implemented/Why did you implemented this:
- Employee model was modificated including foreign keys like role and branch.
- Role table was created for have a best control of employee positions
- Admin table was added

### CODE REVIEW

**Review by VictorElizalde — APPROVED** [review]
LGTM

**Review by MrCano369x — COMMENTED** [review]
LGTM

**Review by MrCano369x — APPROVED** [review]
LGTB

**Review by alexs — APPROVED** [review]
LGTM

**Pull request merged**
