### PR TITLE
controller and model were generated

### LINKED ISSUE #2: Manage branches models
# REQUIREMENTS
Creation of models for manage branches requirements.

### PR DESCRIPTION
**Pull request by femm34**
Co-authored-by: FranH20 <carloshuichi@gmail.com>

# Description
We've created the BRANCH model and controller

### CODE REVIEW

**Review by FranH20 — COMMENTED** [review]
I have changed the version of ruby because it was different. The pr for me is correct.

**Review by FranH20 — COMMENTED** [review]
Its ok for me

**Review by Javi1499 — APPROVED** [review]
Nice job

**Review by FranH20 — COMMENTED** [review]
I accepted this.

**Review by FranH20 — APPROVED** [review]
Accepted

**Review by EliasUR — APPROVED** [review]
lgtm

**Pull request merged**
